# Generated by Django 4.0.6 on 2022-08-27 17:15

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=account.models.get_default_profile_image, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
